config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  devise_for :users
  
  get 'cart/index'

  get 'site/about'

  get 'site/contact'

  get 'site/home'
  
 get '/myprofile' => 'profiles#myprofile'
  
get '/Adminpassword' => 'users#admin_login'

get '/clearCart' => 'cart#clearCart'
  
get '/about' => 'site#about'

get '/contact' => 'site#contact'

get '/home' => 'site#home'

get '/purchase' => 'site#purchase'
  
get '/cart' => 'cart#index'

get '/cart/:id' => 'cart#add'

 get '/cart/remove/:id' => 'cart#remove'

root 'site#home'

  resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
def self.search(search)
  if search
    find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
  else
    find(:all)
  end
end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         has_one :profile
         
         include Gravtastic
         gravtastic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(resource) 
    "/myprofile"
end


end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  
  before_filter :authenticate_user!
  
  def add
    #get the id of a product 
    id = params[:id]
    #if the cart has already been created then the same cart will be used, otherwise a new cart is created. 
    
    if session[:cart]then 
      cart = session[:cart]
    else
      session[:cart]={}
      cart = session[:cart]
    
  end
  #if the product has already been added to the cart the value is incremented 
  #otherwise the value is set to 1.
  
  if cart[id] then
    cart[id] = cart[id]+1
  else 
    cart[id]=1
    end
    
  #redirect the cart display page 
  redirect_to :action => :index
end#end of add method

def clearCart
  #set session varialbe to nil and redirect 
  session[:cart] = nil
  redirect_to :action => :index
end

def remove
  id = params[:id]
  cart = session[:cart]
  cart.delete id
  
 redirect_to :action => :index
end



def index
  #if there is a cart, pass it to the page for display.
 #else pass an empty value
 if session[:cart]then 
   @cart = session[:cart]
 else
   @cart={}
 end

end
  


end

 

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]



  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url, :category)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end


def admin_login
session[:user_id] = 1
session[:cart] = nil
flash[:notice] = "Admin Login Successful!!" 
redirect_to :controller => :items
end



  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
  @user = User.find(current_user.id) 
  @profile = Profile.new 
  @profile.user_id = @user.id
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
#Update the Profiles controller to cater for the redirects
def myprofile
profile = Profile.find_by_user_id(current_user.id)

  if profile.nil?
    redirect_to "/profiles/new"
else
  
@user = User.find(current_user.id)
@profile = Profile.find_by_user_id(@user.id)
redirect_to "/profiles/#{@profile.id}"
end 

end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:firstname, :lastname, :address, :mobile, :user_id)
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
#after_sign_in_path_for is called by devise
def after_sign_in_path_for(user)
"/myprofile" #adjust the returned path as needed end
end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def about
  end

  def contact
  end

  def home
  end
  
  def purchase
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
  def login
  end

  def admin_login
    session[:User_id] = 1
    session[:cart] = nil
    flash[:notice] = "Admin Login Successful!!"
    redirect_to :controller => :items
  end

  def logout
    session[:user_id] = nil
    session[:cart] = nil
    flash[:notice] = "You have successfully logged out!!"
    redirect_to :controller => :items
  end

end

  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper

end
  

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cart/index.html.erb
<h1>Your Cart</h1>

<% if @cart.empty? %>
    <p>Your Cart is empty.</p>
<% end %>

<% total = 0 %>
	
<table class="cart">
    <tr>
        <td class="legend"></td>
        <td class="legend">Item</td>
        <td class="legend">Price</td>
        <td class="legend">Qty</td>
        <td class="legend">Total</td>
    </tr>
	
<% @cart.each do | id, quantity | %>
    <% item = Item.find_by_id(id) %>
    <tr>
        <td>
            <div class="image">
                <%= link_to (image_tag item.image_url, :style => "height:40px"), item %>
            </div>
        </td>
        <td class="title"><%= link_to item.title, item %></td>
        <td class="price"><%= number_to_currency(item.price) %></td>
        <td class="quantity"><%= quantity %><br /></td>
        <td class="price">
        <%= number_to_currency(quantity * item.price, :unit => "€") %>
    </td>
    <td><a href="/cart/remove/<%= item.id %>">Remove from Cart</a></td>
    </tr>
    <% total += quantity * item.price %>
    
<% end %>

    <tr>
        <td colspan="4">
            <div class="total">Total:</div>
        </td>
        <td>
            <div class="price"><%= number_to_currency(total, :unit => "€") %></div>
        </td>
        <td> <a class="btn btn-primary" href="/purchase">Confirm Purchase</a></div></td>
     
    </tr>
</table>

<p>
     <%= link_to 'Continue Shopping', :controller => :items %>
      <%= link_to 'Clear Cart', :controller => "cart", :action => "clearCart" %>
</p>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Catalog</h1>
<table class="catalog">
<% @items.each do |item| %> <tr>
<td>
<div class="image">
<%= link_to (image_tag item.image_url, :style => "height:100px"), item %> </div>
</td> <td>
<div class="title">
<%= link_to item.title, item %>
</div>
<div class="description">
<%=h item.description %> </div>
<div class="price">
<%= number_to_currency(item.price, :unit => "€") %>
</div>
<div class="links">
  
  <% if session[:User_id] == 1 %>
<%= link_to 'Edit', edit_item_path(item) %> |
<%= link_to 'Destroy', item, :confirm => 'Are you sure?', :method => :delete %>
<% else %>
<a href = "/cart/<%= item.id %>">Add to cart</a></br></br>
<% end %>
</div>
</td> </tr>
<% end %> </table>

 <% if session[:User_id] == 1 %>
<p><%= link_to 'New item', new_item_path %></p>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @item.image_url %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>OnLicense</title>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %> <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<link href="css/bootstrap.min.css" rel="stylesheet">
</head> <body>
  <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

  
     <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    
                </button>
                <a class="navbar-brand" href="/home">OnLicense</a>
                
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/about">About</a>
                    </li>
                    <li>
                        <a href="/users/sign_in">Login</a>
                    </li>
                  <!--  <li>
                        <a href="/users/sign_out">Logout</a>
                    </li> this button and other original logout buttons that were implemneted in the early stages of dev were
                    removed as 'sign out' functionality was implemented when the Devise gem was utilised-->
                    <li>
                        <a href="/users/sign_up">Sign Up</a>
                    </li>
                    
                   
                </ul>
                
                <div class="navbar-form navbar-right">
                <div class="input-group">
                <%= form_tag(items_path, :method => "get", id: "search-form", html: {class: 'form-group'}) do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Items", class: "form-control" %>
        <span class="input-group-btn">
      <%= submit_tag "Search", :class => 'btn btn-default',:name => nil%>
        <span class="glyphicon glyphicon-search"></span>
                    </span>
<% end %>
</div>
</div>

                
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
        
    </nav>
<div id='header'>
<!-- Header Image Displayes here -->
</div>
<div id='menu'>
<div id="navbar">
  <ul>
   <li><a href = "/home">Home</a></li>
  <li><a href = "/items">Products</a></li>
  <li><a href="/about">About</a></li>
  <li><a href="/contact">Contact Us</a></li>
  <li><a href="/users/sign_in">Login</a></li>
  <!--<li><a href="/users/sign_out">Logout</a></li>-->
   </ul>
   </div>
</div>

    
<div id='container'>
 
<div id='content'>
<p class="notice"><%= flash[:notice] %></p> 


<%= yield %>


<% if user_signed_in? %>
<%= image_tag current_user.gravatar_url %>
<div>Welcome to Onlicense <%= current_user.email %> (<%= link_to 'Sign out', destroy_user_session_path, :method => :delete
%>)</div> <% else %>
<%= link_to 'Register', new_user_registration_path %> or <%= link_to 'Sign in', new_user_session_path %> <% end %>


</div> <!--This section is the main content body-->
<!--<div id='first-column'> <div class="loginbox">
<h2 class="BoxHeaders">Login Here....</h2> </div>
<div class="searchbox">
<h2 class="BoxHeaders">Search Catalog</h2>
</div> </div>
</div>-->
<div id='footer'>
<h6 class="footertext">&copy; Onlicense &trade; 2015</h6> </div>

      <!--Rails.env.development? is true only in a development environment, so the embedded <Ruby-></Ruby>

    </div> -->
</body> </html>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile %>
  </div>
 
 <!-- <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>-->
  
  

    
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Address</th>
      <th>Mobile</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.firstname %></td>
        <td><%= profile.lastname %></td>
        <td><%= profile.address %></td>
        <td><%= profile.mobile %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Firstname:</strong>
  <%= @profile.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @profile.lastname %>
</p>

<p>
  <strong>Address:</strong>
  <%= @profile.address %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @profile.mobile %>
</p>
<!--
<p>
  <strong>User:</strong>
  <%= @profile.user %>
</p>
-->

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', home_path%>

app/views/site/about.html.erb
  <body>
  <h1>About us</h1>
  <div class="aboutcontainer">
  </br>
  <div class = "img">
  <%=image_tag("about_banner.png", alt: "Wine Image")%>
  </div>
  </br>
<p>
<b>Home Page Article</b>
Worldwide off-license onine - Your Premier Online off-license is an online liquor store with a wide selection of alcoholic beverages to choose from. We carry everything from exquisite wines, champagne and spirits to specialty beer and gift baskets - all delivered to you at affordable prices. We also offer drive-in pick up as a quick and convenient option for our local customers. x makes it easier than ever to buy alcohol online, so check out our huge selection today!
</br></br><b>Something for Every Occasion</b>
Life is full of reasons to celebrate, and Worldwide Wine & Spirit has something for every occasion. Whether you need a full spread of alcohol for a big party or just a couple bottles of wine for relaxing at home, we make it easy for you to buy liquor online. By taking our store online, we are able to offer you much more variety than you’ll find at your local store. We carry both imported and domestic beverages in our online alcohol store so you can find all of your favorite specialty drinks without the hassle of driving around from store to store to find them. With hundreds of brands to choose from, you’ll find all of your favorite wine, beer, spirits and more from all over the world in our online liquor store. Worldwide Wine & Spirits is your passport to a world of good taste!
Unsure of what to go with? Not an issue. World Wine & Spirits provides accurate knowledge of tastes and mixture to best fit your taste preference. From our weekly emails and specials to our active industry blog, why go to the store? We give you access to the latest and greatest all at your finger tips! Making the choice to buy alcohol online has never been easier.
</br></br><b>Worldwide Wine & Spirits’ Commitment to Excellent Service</b>
As one of the premier destinations to buy liquor online, we pride ourselves in the quality of service we offer our customers. We want you to get the most value out of your purchase when you order alcohol online, which is why we are committed to providing you with great products from our online alcohol store at excellent prices. Worldwide Wine & Spirits is also the first liquor store online to offer drive-in pickup. Stop in and see our wonderful store or check out our selection and services online and let us know if you have any questions - our expert staff is available to assist you!
</p>
</div>
</body>

app/views/site/contact.html.erb
<h1>Contact Us</h1>
  <div class="aboutcontainer">
  </br>
  <div class = "img">
<%=image_tag("contactus.jpg", alt: "Example Image")%>
</div>
</br>
<p>Want to know more about our services or products? Our friendly and knowledgeable staff is here to answer any questions or provide recommendations for you. We can also here to respond to any other inquiries you may have regarding a transaction or delivery status. Call us at (860) 276-5801 or click one of the links below to send an email and someone will respond to you shortly!
</br></br>
<b>Visit us in-store!</b></br>
Want to come in a see our amazing collection for yourself? We’d love to see you! At Off-license.com, we place value in getting to know our customers. Stop in and see our wonderful store, meet the staff, and browse our full collection of wine, beer, and liquor.  We also offer 
drive-in and pick-up service. We are located at IFSC, Dublin, Ireland.</p>
</div>

app/views/site/home.html.erb
<body>

    <!-- Page Content -->
    <div class="container">

        <div class="row">

          <!--  <div class="col-md-3">
                <p class="lead">Shop Name</p>
                <div class="list-group">
                    <a href="#" class="list-group-item">Category 1</a>
                    <a href="#" class="list-group-item">Category 2</a>
                    <a href="#" class="list-group-item">Category 3</a>
                </div>
            </div>-->

            <div class="col-md-9">

                <div class="row carousel-holder">

                    <div class="col-md-12">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="item active">
                                    <img class="slide-image" src="assets/about_banner.jpg" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="assets/spiritsbanner.jpg" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="assets/beerbanner.jpg" alt="">
                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    </div>

                </div>

                <div class="row">

                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <img src="assets/bud.jpg" alt="">
                            <div class="caption">
                                <h4 class="pull-right">€10.55</h4>
                                <h4><a href="items/1">Budweiser 6 pack</a>
                                </h4>
                                <p>This offer is only available while it lasts. <a target="_blank" href="http://www.bootsnipp.com">Bootsnipp - http://bootsnipp.com</a>.</p>
                            </div>
                            <div class="ratings">
                                <p class="pull-right">15 reviews</p>
                                <p>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <img src="assets/Guiness.jpg" alt="">
                            <div class="caption">
                                <h4 class="pull-right">€20.00</h4>
                                <h4><a href="items/4">Guiness</a>
                                </h4>
                                <p>Get the last of the summer stout while the offer lasts.</p>
                            </div>
                            <div class="ratings">
                                <p class="pull-right">12 reviews</p>
                                <p>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star-empty"></span>
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <img src="assets/Coors.jpg" alt="Coors bottles picture">
                            <div class="caption">
                                <h4 class="pull-right">€15.00</h4>
                                <h4><a href="items/3">Coors Light</a>
                                </h4>
                                <p>Looling for a light refreshing taste this summer? check out out coors deals.</p>
                            </div>
                            <div class="ratings">
                                <p class="pull-right">31 reviews</p>
                                <p>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star-empty"></span>
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <img src="assets/Heineken.jpg" alt="">
                            <div class="caption">
                                <h4 class="pull-right">€20.00</h4>
                                <h4><a href="items/5">Heineken</a>
                                </h4>
                                <p>Check out our latest deals on premium beers, free backpack included.</p>.</p>
                            </div>
                            <div class="ratings">
                                <p class="pull-right">6 reviews</p>
                                <p>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star-empty"></span>
                                    <span class="glyphicon glyphicon-star-empty"></span>
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <img src="assets/spirits.jpg" alt="jager image">
                            <div class="caption">
                                <h4 class="pull-right">€19.00</h4>
                                <h4><a href="items/6">Spirits</a>
                                </h4>
                                <p>We have some great deals on spirits this August....</p>
                            </div>
                            <div class="ratings">
                                <p class="pull-right">18 reviews</p>
                                <p>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star-empty"></span>
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <h4><a href="/items">Like what you see?</a>
                        </h4>
                        <p>Why not explore our online store and pre-order your alcohol now..<a target="_blank" href="/items">this tutorial</a> on how to build a working review system for your online store!</p>
                        <a class="btn btn-primary" href="/items">Shop</a>
                    </div>

                </div>

            </div>

        </div>

    </div>
    <!-- /.container -->

    <div class="container">

        <hr>

        <!-- Footer -->
       

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>